from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from datetime import date,datetime
import random
sys.path.insert(1,'F:\\accenture_interview_project\\database_connection')
sys.path.insert(2,'F:\\accenture_interview_project\\modelling_files')
import db_funcy 
import modelling_file 
today=date.today()
ct = datetime.now()
num=random.randint(1,10001)




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(876, 638)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(770, 10, 91, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("F:\\accenture_interview_project\\GUI_files\\Images\\buff (1).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 151, 21))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(340, 120, 151, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 70, 151, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 120, 151, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(570, 90, 151, 21))
        self.label_7.setObjectName("label_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(340, 140, 201, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(50, 140, 241, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(50, 190, 761, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 170, 151, 21))
        self.label_8.setObjectName("label_8")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 90, 241, 31))
        self.textBrowser.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser.setLineWidth(1)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setText(str(num))
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(340, 90, 201, 31))
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser_2.setLineWidth(1)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_2.setText(str(today))
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(570, 120, 191, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(50, 290, 241, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(50, 240, 241, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(340, 240, 201, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(580, 260, 191, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(50, 220, 151, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(340, 220, 151, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(580, 240, 151, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(50, 270, 151, 21))
        self.label_12.setObjectName("label_12")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(650, 340, 111, 31))
        self.pushButton.setStyleSheet("background-color:#33b249;\n"
"color:white;\n"
"border-radius:12px;\n"
"font: bold;")
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.click_submit)


        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 400, 101, 31))
        self.pushButton_2.setStyleSheet("background-color:#33b249;\n"
"color:white;\n"
"border-radius:12px;\n"
"font: bold;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.measure)

        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(760, 400, 101, 31))
        self.pushButton_4.setStyleSheet("background-color:#33b249;\n"
"color:white;\n"
"border-radius:12px;\n"
"font: bold;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(660, 460, 101, 31))
        self.pushButton_5.setStyleSheet("background-color:#33b249;\n"
"color:white;\n"
"border-radius:12px;\n"
"font: bold;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(400, 530, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:#0d0d0d;\n"
"color:white;\n"
"font: bold;")
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(60, 410, 151, 21))
        self.label_18.setObjectName("label_18")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(340, 290, 201, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(340, 270, 151, 21))
        self.label_19.setObjectName("label_19")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(60, 430, 321, 51))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(620, 370, 181, 91))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("F:\\accenture_interview_project\\GUI_files\\Images\\arrow-removebg-preview.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(30, 30, 201, 31))
        self.label_13.setStyleSheet("background-color:#DA70D6;\n"
"color:white;\n"
"border-radius:12px;\n"
"font: bold;")
        self.label_13.setScaledContents(False)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(40, 370, 211, 31))
        self.label_14.setStyleSheet("background-color:#DA70D7;\n"
"color:white;\n"
"border-radius:12px;\n"
"font: bold;")
        self.label_14.setScaledContents(False)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(330, 510, 81, 81))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("F:\\accenture_interview_project\\GUI_files\\Images\\model.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(60, 490, 221, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.comboBox.addItem("Others")
        self.comboBox.addItem("Farmer")
        self.comboBox.addItem("Production Firm")
        self.comboBox_2.addItem("",[])
        self.comboBox_2.addItem("Milk Powder", ["Brix"])
        self.comboBox_2.addItem("Chili" ,["Service Unavialable"])
        self.comboBox_2.addItem("Banana",["Service Unavialable"])
        self.comboBox_2.addItem("Paddy",["Service Unavialable"])
        self.comboBox_2.addItem("Pepper",["Service Unavialable"])
        self.comboBox_2.addItem("Coconut",["Service Unavialable"])
        self.comboBox_2.activated.connect(self.combo3)
    def combo3(self,index):
        self.comboBox_3.clear()
        self.comboBox_3.addItems(self.comboBox_2.itemData(index))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Sample-ID"))
        self.label_4.setText(_translate("MainWindow", "Contact"))
        self.label_5.setText(_translate("MainWindow", "Entry Date"))
        self.label_6.setText(_translate("MainWindow", "Name"))
        self.label_7.setText(_translate("MainWindow", "Submiiter"))
        self.label_8.setText(_translate("MainWindow", "Address"))
        self.label_9.setText(_translate("MainWindow", "Village"))
        self.label_10.setText(_translate("MainWindow", "District"))
        self.label_11.setText(_translate("MainWindow", "Pincode"))
        self.label_12.setText(_translate("MainWindow", "Crop"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.pushButton_2.setText(_translate("MainWindow", "Measure"))
        self.pushButton_4.setText(_translate("MainWindow", "Cancel"))
        self.pushButton_5.setText(_translate("MainWindow", "Print"))
        self.label_3.setText(_translate("MainWindow", "Status Update !!"))
        self.label_18.setText(_translate("MainWindow", "File Path"))
        self.label_19.setText(_translate("MainWindow", "Parameter"))
        self.label_13.setText(_translate("MainWindow", "Application details"))
        self.label_14.setText(_translate("MainWindow", "Paste  file location here"))

    def click_submit(self):
        #getting the text from labels
        name=self.lineEdit_4.text()
        submitter=self.comboBox.currentText()
        contact=self.lineEdit_3.text()
        full_address=self.lineEdit_6.text()
        village=self.lineEdit_5.text()
        district=self.lineEdit_7.text()
        pin=self.lineEdit_8.text()
        crop=self.comboBox_2.currentText()
        parameter=self.comboBox_3.currentText()
        entry_date=str(ct)
        #saving data in to an excel database
        db_funcy.db_connection()
        db_funcy.insert_data(query=db_funcy.query,data=(num,name,entry_date,submitter,contact,full_address,village,district,pin,crop,parameter))
        #clearing the labels
        self.lineEdit_3.clear()
        self.lineEdit_6.clear()
        self.lineEdit_7.clear()
        self.lineEdit_4.clear()
        self.lineEdit_8.clear()
        self.lineEdit_5.clear()

    def measure(self):
        # wd=wd="D:\\GCA_application"
        path=self.lineEdit_13.text()
        target=self.comboBox_2.currentText()
        val=modelling_file.model_func(path=path,target=self.comboBox_3.currentText())
        self.label_3.setText(f"{target} Percentage for sample is {round(val,2)}%")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
